version: "3" 
services: 
  db:
    image: postgres
    environment:
      POSTGRES_USER: ilia
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true